# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
alias ls='ls -F'
. /etc/bash_completion.d/git
. /etc/bash_completion.d/git-flow

# display current GIT branch
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
WHITE="\[\033[1;37m\]"
YELLOW="\[\033[0;33m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
CLR="\[\033[0m\]"
PS1="[\u@\h \W ${YELLOW}\$(parse_git_branch)${CLR}]\\$ "
